### ISSUE TITLE
Remove unnecessary email field in /auth/forgotmypassword

### ISSUE THREAD

**Issue by ulissesferreira** [upframe/api#40]
Right now this endpoint is expecting 3 inputs: email, new password and the token sent via email. We don't want to depend the current email to perform the change since this is an extra step for the user.

Let's make the tokens harder to crack (implement bruteforce protection or had an expiration time or max attempts) and remove the need to input the email address of the account they want to change the email of.

**Comment by fabiofcferreira** [comment]
There are two phases in reseting the user account password.
In the first step, a request is made with the corresponding JSON data
`
{
  email: 'useremail@domain.tld'
}
`

This request tells the API to send a password reset email in case there's an account with the given email.
Here it is impossible to remove the email from the equation obviously (so that not logged users can also reset their password).

In the second phase, we can definitely remove the email field, and use the database email value corresponding to the token given.
I'll quickly work on that as soon as possible.

Great issue 👍
